# Generated by Django 3.2.7 on 2021-09-03 17:33

import autoslug.fields
from django.db import migrations

from ..models import Recipe

def migrate_data_forward(apps, schema_editor):
    for instance in Recipe.objects.all():
        print("Generating slug for %s" % instance)
        instance.save() # Will trigger slug update

def migrate_data_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
