# Generated by Django 3.2.7 on 2021-09-03 21:23

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_recipe_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='dish_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.dishtype'),
        ),
    ]
