# Generated by Django 3.2.7 on 2021-09-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('TBSP', 'Tbsp'), ('TSP', 'Tsp'), ('OZ', 'Oz'), ('LB', 'Lb'), ('CUP', 'Cup')], max_length=4, null=True),
        ),
    ]
