# Generated by Django 3.2.7 on 2021-09-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('TBSP', 'tbsp.'), ('TSP', 'tsp.'), ('OZ', 'oz'), ('LB', 'lb'), ('CUP', 'cup')], max_length=4, null=True),
        ),
    ]
