# Generated by Django 3.2.7 on 2021-09-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_ingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('TBSP', 'tbsp.'), ('TSP', 'tsp.'), ('OZ', 'oz'), ('LB', 'lb'), ('CUP', 'cup'), ('BUNCH', 'bunch')], max_length=5, null=True),
        ),
    ]
